/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testepratico;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class AppReceitasDespesas extends javax.swing.JFrame {

    /**
     * Creates new form AppReceitasDespesas
     */
    public AppReceitasDespesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogRegistar = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerAnoRegistar = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxMesRegistar = new javax.swing.JComboBox<>();
        jRadioButtonDespesa = new javax.swing.JRadioButton();
        jRadioButtonReceita = new javax.swing.JRadioButton();
        jButtonRegistar = new javax.swing.JButton();
        jDialogVer = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerAnoVer = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxMesesVer = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVerDespesas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabelReceita = new javax.swing.JLabel();
        jLabelDespesa = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonTerminar = new javax.swing.JButton();
        jButtonRegistarRD = new javax.swing.JButton();
        jButtonVerRD = new javax.swing.JButton();

        jDialogRegistar.setTitle("Registo Receitas e Despesas");
        jDialogRegistar.setMinimumSize(new java.awt.Dimension(500, 400));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhe Receita"));

        jLabel3.setText("Tipo de Receita:");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venda bens imóveis", "Alimentação" }));

        jLabel4.setText("Dia:");

        jLabel5.setText("Valor:");

        jTextFieldValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldValor.setText("0");

        jLabel6.setText("€");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(50, 50, 50)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ano:");

        jSpinnerAnoRegistar.setModel(new javax.swing.SpinnerNumberModel(2017, 2017, 2200, 1));
        jSpinnerAnoRegistar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSpinnerAnoRegistarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mês:");

        jComboBoxMesRegistar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBoxMesRegistar.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxMesRegistarPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        buttonGroup1.add(jRadioButtonDespesa);
        jRadioButtonDespesa.setText("Despesa");

        buttonGroup1.add(jRadioButtonReceita);
        jRadioButtonReceita.setText("Receita");

        jButtonRegistar.setText("Registar");
        jButtonRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogRegistarLayout = new javax.swing.GroupLayout(jDialogRegistar.getContentPane());
        jDialogRegistar.getContentPane().setLayout(jDialogRegistarLayout);
        jDialogRegistarLayout.setHorizontalGroup(
            jDialogRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogRegistarLayout.createSequentialGroup()
                .addGroup(jDialogRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogRegistarLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerAnoRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxMesRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogRegistarLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jRadioButtonReceita)
                        .addGap(54, 54, 54)
                        .addComponent(jRadioButtonDespesa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDialogRegistarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jDialogRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRegistar)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jDialogRegistarLayout.setVerticalGroup(
            jDialogRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogRegistarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jDialogRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerAnoRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxMesRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonDespesa)
                    .addComponent(jRadioButtonReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRegistar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jDialogVer.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ano:");

        jSpinnerAnoVer.setModel(new javax.swing.SpinnerNumberModel(2017, 2017, 2200, 1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Mês:");

        jComboBoxMesesVer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBoxMesesVer.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxMesesVerPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jTableVerDespesas.setAutoCreateRowSorter(true);
        jTableVerDespesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Dia", "Tipo", "Receita", "Despesa"
            }
        ));
        jScrollPane1.setViewportView(jTableVerDespesas);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Saldo:");

        jLabelReceita.setBackground(new java.awt.Color(255, 255, 255));
        jLabelReceita.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelReceita.setText("0");
        jLabelReceita.setOpaque(true);

        jLabelDespesa.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDespesa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDespesa.setText("0");
        jLabelDespesa.setOpaque(true);

        jLabelTotal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotal.setText("0");
        jLabelTotal.setOpaque(true);

        javax.swing.GroupLayout jDialogVerLayout = new javax.swing.GroupLayout(jDialogVer.getContentPane());
        jDialogVer.getContentPane().setLayout(jDialogVerLayout);
        jDialogVerLayout.setHorizontalGroup(
            jDialogVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jDialogVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogVerLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerAnoVer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxMesesVer, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogVerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialogVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialogVerLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogVerLayout.createSequentialGroup()
                        .addComponent(jLabelReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        jDialogVerLayout.setVerticalGroup(
            jDialogVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jDialogVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinnerAnoVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxMesesVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de Receitas e Despesas");

        jToolBar1.setRollover(true);

        jButtonTerminar.setText("Terminar");
        jButtonTerminar.setFocusable(false);
        jButtonTerminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTerminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonTerminar);

        jButtonRegistarRD.setText("Receitas/Despesas");
        jButtonRegistarRD.setFocusable(false);
        jButtonRegistarRD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRegistarRD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRegistarRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistarRDActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonRegistarRD);

        jButtonVerRD.setText("Ver");
        jButtonVerRD.setFocusable(false);
        jButtonVerRD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVerRD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVerRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerRDActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonVerRD);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 275, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerminarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonTerminarActionPerformed

    private void jButtonRegistarRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarRDActionPerformed
        lerTiposDespesa();
        jDialogRegistar.setVisible(true);
    }//GEN-LAST:event_jButtonRegistarRDActionPerformed

    private void jButtonVerRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerRDActionPerformed
        jDialogVer.setVisible(true);
    }//GEN-LAST:event_jButtonVerRDActionPerformed

    private void jComboBoxMesRegistarPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxMesRegistarPopupMenuWillBecomeInvisible
        int mes = jComboBoxMesRegistar.getSelectedIndex();
        jComboBoxDia.removeAllItems();
        for (int i=1;i<=diasMes(mes);i++){
            jComboBoxDia.addItem(""+i);
        }
    }//GEN-LAST:event_jComboBoxMesRegistarPopupMenuWillBecomeInvisible

    private void jButtonRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarActionPerformed
        int ano = jSpinnerAnoRegistar.getSelectedIndex()+1);
        int mes = jComboBoxMesRegistar.getSelectedIndex()+1;
        String tipo = jComboBoxTipo.getSelectedItem().toString();
        int dia = jComboBoxDia.getSelectedIndex()+1;
        double valor = Double.parseDouble(jTextFieldValor.getText());
        String receitadespesa = jComboBoxTipo.getSelectedItem().toString();
        
        inserirRegisto(ano, mes, tipo, dia, valor, receitadespesa);
    }//GEN-LAST:event_jButtonRegistarActionPerformed

    private void jComboBoxMesesVerPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxMesesVerPopupMenuWillBecomeInvisible
        int mes = jComboBoxMesesVer.getSelectedIndex()+1;
        lerDespesasPorMes(mes);
    }//GEN-LAST:event_jComboBoxMesesVerPopupMenuWillBecomeInvisible

    private void jSpinnerAnoRegistarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSpinnerAnoRegistarAncestorAdded
        int ano = jSpinnerAnoRegistar.getSelectedIndex()+1);
    }//GEN-LAST:event_jSpinnerAnoRegistarAncestorAdded

    private void lerDespesasPorMes(int mes){
        String url = "jdbc:sqlite:BDReceitasDespesas";
        Connection con;
        Statement stmt;
        DefaultTableModel modelo = (DefaultTableModel)jTableVerDespesas.getModel();
        modelo.setRowCount(0);
        try {
            Class.forName("org.sqlite.JDBC");
        } catch(java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }
        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from RegistoDespesa where ano = "+ano );
            ResultSet rs = stmt.executeQuery("select * from RegistoDespesa where mes = "+mes );
            double totaldes = 0;
            double totalrec = 0;
            double total = 0;
            while (rs.next()) {
            		int dia = rs.getInt("Dia");
                        String tipo = rs.getString("Tipo");
                        String receitadespesa = rs.getString("ReceitaDespesa");
                        totaldes = totaldes + receitadespesa;
                        totalrec = totalrec + receitadespesa;
                        total = totalrec - totaldes;
                        Object rowData[] = {dia,tipo,receitadespesa};
                        modelo.addRow(rowData);
	    }
            jLabelDespesa.setText(""+totaldes);
            jLabelReceita.setText(""+totalrec);
            jLabelTotal.setText(""+total);
            stmt.close();
            con.close();
        } catch(SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
        
    }
    
    private void inserirRegisto(int ano, int mes, String tipo, int dia, double valor, String receitadespesa){
        String url = "jdbc:sqlite:BDReceitasDespesas";
        Connection con;
        Statement stmt;

        try {
            Class.forName("org.sqlite.JDBC");
        } catch(java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }

        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            stmt.executeUpdate("INSERT INTO RegistoDespesa " +
            	 "VALUES ("+ano+","+mes+",'"+tipo+"',"+dia+","+valor+",'"+receitadespesa+"')");
        	 
            stmt.close();
            con.close();
            

        } catch(SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
        
    }
    
    private int diasMes(int mes){
        int m[] = {31,29,31,30,31,30,31,31,30,31,30,31};
        return m[mes];
    }
    
    private void lerTiposDespesa(){
        String url = "jdbc:sqlite:BDReceitasDespesas";
        Connection con;
        Statement stmt;
        jComboBoxTipo.removeAllItems();
        try {
            Class.forName("org.sqlite.JDBC");
        } catch(java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }
        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from TipoDespesa");
            jComboBoxTipo.addItem("-- Escolha o Tipo de Despesa --");
            while (rs.next()) {	
            		String tipo = rs.getString("Tipo");
                        jComboBoxTipo.addItem(tipo);
	    }
            stmt.close();
            con.close();
        } catch(SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppReceitasDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppReceitasDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppReceitasDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppReceitasDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppReceitasDespesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonRegistar;
    private javax.swing.JButton jButtonRegistarRD;
    private javax.swing.JButton jButtonTerminar;
    private javax.swing.JButton jButtonVerRD;
    private javax.swing.JComboBox<String> jComboBoxDia;
    private javax.swing.JComboBox<String> jComboBoxMesRegistar;
    private javax.swing.JComboBox<String> jComboBoxMesesVer;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JDialog jDialogRegistar;
    private javax.swing.JDialog jDialogVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDespesa;
    private javax.swing.JLabel jLabelReceita;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonDespesa;
    private javax.swing.JRadioButton jRadioButtonReceita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerAnoRegistar;
    private javax.swing.JSpinner jSpinnerAnoVer;
    private javax.swing.JTable jTableVerDespesas;
    private javax.swing.JTextField jTextFieldValor;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
