/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exbd2017;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jfig
 */
public class AppGestaoArtigos extends javax.swing.JFrame {

    /**
     * Creates new form AppGestaoArtigos
     */
    public AppGestaoArtigos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogInserirArtigo = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jTextFieldPreco = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonInserir = new javax.swing.JButton();
        jDialogVerTudo = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArtigos = new javax.swing.JTable();
        jButtonAlterar = new javax.swing.JButton();
        jDialogInserirArtigoBD = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldQuantidade1 = new javax.swing.JTextField();
        jTextFieldPreco1 = new javax.swing.JTextField();
        jTextFieldNome1 = new javax.swing.JTextField();
        jButtonInserir1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAplicacao = new javax.swing.JMenu();
        jMenuItemAplicacaoTerminar = new javax.swing.JMenuItem();
        jMenuGestaoArtigos = new javax.swing.JMenu();
        jMenuItemGestaoArtigosInserir = new javax.swing.JMenuItem();
        jMenuItemGestaoArtigosInserirBD = new javax.swing.JMenuItem();
        jMenuItemGestaoArtigosVerTodos = new javax.swing.JMenuItem();

        jDialogInserirArtigo.setTitle("Inserir Artigo");
        jDialogInserirArtigo.setLocationByPlatform(true);
        jDialogInserirArtigo.setMinimumSize(new java.awt.Dimension(400, 265));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Artigo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 153, 255))); // NOI18N

        jLabel1.setText("Nome:");

        jLabel2.setText("Preço:");

        jLabel3.setText("Quantidade:");

        jButtonInserir.setText("Inserir");
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldPreco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldQuantidade))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(14, 14, 14)
                .addComponent(jButtonInserir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogInserirArtigoLayout = new javax.swing.GroupLayout(jDialogInserirArtigo.getContentPane());
        jDialogInserirArtigo.getContentPane().setLayout(jDialogInserirArtigoLayout);
        jDialogInserirArtigoLayout.setHorizontalGroup(
            jDialogInserirArtigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogInserirArtigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogInserirArtigoLayout.setVerticalGroup(
            jDialogInserirArtigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogInserirArtigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogVerTudo.setTitle("Visualizar");
        jDialogVerTudo.setLocationByPlatform(true);
        jDialogVerTudo.setMinimumSize(new java.awt.Dimension(400, 300));

        jTableArtigos.setAutoCreateRowSorter(true);
        jTableArtigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableArtigos);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogVerTudoLayout = new javax.swing.GroupLayout(jDialogVerTudo.getContentPane());
        jDialogVerTudo.getContentPane().setLayout(jDialogVerTudoLayout);
        jDialogVerTudoLayout.setHorizontalGroup(
            jDialogVerTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerTudoLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jDialogVerTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jDialogVerTudoLayout.setVerticalGroup(
            jDialogVerTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogVerTudoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterar)
                .addGap(48, 48, 48))
        );

        jDialogInserirArtigoBD.setTitle("Inserir Artigo");
        jDialogInserirArtigoBD.setLocationByPlatform(true);
        jDialogInserirArtigoBD.setMinimumSize(new java.awt.Dimension(400, 265));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Artigo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 153, 255))); // NOI18N

        jLabel4.setText("Nome:");

        jLabel5.setText("Preço:");

        jLabel6.setText("Quantidade:");

        jButtonInserir1.setText("Inserir BD");
        jButtonInserir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldPreco1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jTextFieldNome1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldQuantidade1))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonInserir1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGap(14, 14, 14)
                .addComponent(jButtonInserir1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogInserirArtigoBDLayout = new javax.swing.GroupLayout(jDialogInserirArtigoBD.getContentPane());
        jDialogInserirArtigoBD.getContentPane().setLayout(jDialogInserirArtigoBDLayout);
        jDialogInserirArtigoBDLayout.setHorizontalGroup(
            jDialogInserirArtigoBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogInserirArtigoBDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogInserirArtigoBDLayout.setVerticalGroup(
            jDialogInserirArtigoBDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogInserirArtigoBDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão Artigos");

        jMenuAplicacao.setText("Aplicação");

        jMenuItemAplicacaoTerminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAplicacaoTerminar.setText("Terminar");
        jMenuItemAplicacaoTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAplicacaoTerminarActionPerformed(evt);
            }
        });
        jMenuAplicacao.add(jMenuItemAplicacaoTerminar);

        jMenuBar1.add(jMenuAplicacao);

        jMenuGestaoArtigos.setText("Gestão Artigos");

        jMenuItemGestaoArtigosInserir.setText("Inserir");
        jMenuItemGestaoArtigosInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestaoArtigosInserirActionPerformed(evt);
            }
        });
        jMenuGestaoArtigos.add(jMenuItemGestaoArtigosInserir);

        jMenuItemGestaoArtigosInserirBD.setText("Inserir BD");
        jMenuItemGestaoArtigosInserirBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestaoArtigosInserirBDActionPerformed(evt);
            }
        });
        jMenuGestaoArtigos.add(jMenuItemGestaoArtigosInserirBD);

        jMenuItemGestaoArtigosVerTodos.setText("Ver Todos");
        jMenuItemGestaoArtigosVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestaoArtigosVerTodosActionPerformed(evt);
            }
        });
        jMenuGestaoArtigos.add(jMenuItemGestaoArtigosVerTodos);

        jMenuBar1.add(jMenuGestaoArtigos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGestaoArtigosInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestaoArtigosInserirActionPerformed
        jDialogInserirArtigo.setVisible(true);
    }//GEN-LAST:event_jMenuItemGestaoArtigosInserirActionPerformed

    private void jMenuItemGestaoArtigosVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestaoArtigosVerTodosActionPerformed
//        carregaArtigosTabela();
        lerTabela();
        jDialogVerTudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemGestaoArtigosVerTodosActionPerformed

    private void carregaArtigosTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTableArtigos.getModel();
        modelo.setRowCount(0);
        ArrayList<Artigo> tArtigos = g.gettArtigos();
        for (Artigo a : tArtigos) {
            Object[] rowData = {
                a.getNome(),
                a.getPreco(),
                a.getQuantidade()
            };
            modelo.addRow(rowData);
        }

    }

    private void jMenuItemAplicacaoTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAplicacaoTerminarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemAplicacaoTerminarActionPerformed

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        String nome = jTextFieldNome.getText();
        double preco = Double.parseDouble(jTextFieldPreco.getText());
        int quantidade = Integer.parseInt(jTextFieldQuantidade.getText());

        g.addArtigo(nome, preco, quantidade);

//        Artigo a = new Artigo(nome, preco, quantidade);
//        g.addArtigo(a);
        limpaCamposArtigo();
    }//GEN-LAST:event_jButtonInserirActionPerformed

    private void jButtonInserir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserir1ActionPerformed
        String nome = jTextFieldNome1.getText();
        double preco = Double.parseDouble(jTextFieldPreco1.getText());
        int quantidade = Integer.parseInt(jTextFieldQuantidade1.getText());
        
        if (jButtonInserir1.getText().equals("Inserir BD")){
            inserirArtigoBD(nome, preco, quantidade);
        } else {    // Alterar
            alterarArtigoBD(nomePesquisa, nome, preco, quantidade);
            jButtonInserir1.setText("Inserir BD");
            jDialogInserirArtigoBD.setVisible(false);
            lerTabela();
//            jDialogVerTudo.setVisible(true);
        }
        
        limpaCamposArtigoBD();
    }//GEN-LAST:event_jButtonInserir1ActionPerformed

    private void jMenuItemGestaoArtigosInserirBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestaoArtigosInserirBDActionPerformed
        jDialogInserirArtigoBD.setVisible(true);
    }//GEN-LAST:event_jMenuItemGestaoArtigosInserirBDActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        int linha = jTableArtigos.getSelectedRow();
        if (linha > -1){
            String nome = jTableArtigos.getValueAt(linha, 0).toString();
            nomePesquisa = nome;
            double preco = Double.parseDouble(jTableArtigos.getValueAt(linha, 1).toString());
            int quantidade = Integer.parseInt(jTableArtigos.getValueAt(linha, 2).toString());
            
            jTextFieldNome1.setText(nome);
            jTextFieldPreco1.setText(""+preco);
            jTextFieldQuantidade1.setText(""+quantidade);
            
            jDialogInserirArtigoBD.setVisible(true);
            
            jButtonInserir1.setText("Alterar");
//            jDialogVerTudo.setVisible(false);
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void lerTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTableArtigos.getModel();
        modelo.setRowCount(0);

        String url = "jdbc:sqlite:BDArtigos.db";
        Connection con;
        Statement stmt;

        try {
            Class.forName("org.sqlite.JDBC");
        } catch (java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }

        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String nomeTabela = "Artigos";
            ResultSet rs = stmt.executeQuery("select * from " + nomeTabela);
            
            while (rs.next()) {
                Object[] rowData = {
                    rs.getString("Nome"),
                    rs.getDouble("Preco"),
                    rs.getInt("Quantidade")
                };
                modelo.addRow(rowData);
            }
            stmt.close();
            con.close();

        } catch (SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
    }

    private void inserirArtigoBD(String nome, double preco, int quantidade) {
        String url = "jdbc:sqlite:BDArtigos.db";
        Connection con;
        Statement stmt;

        try {
            Class.forName("org.sqlite.JDBC");
        } catch (java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }

        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();

            // Exemplo: insert into Artigos('café', 0.4,123)
            stmt.executeUpdate("INSERT INTO Artigos "
                    + "VALUES ('" + nome + "',"
                    + preco + ", "
                    + quantidade + ")");

            stmt.close();
            con.close();

        } catch (SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
    }
    private void alterarArtigoBD(String nomePesquisa,String nome, double preco, int quantidade) {
        String url = "jdbc:sqlite:BDArtigos.db";
        Connection con;
        Statement stmt;

        try {
            Class.forName("org.sqlite.JDBC");
        } catch (java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }

        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();

            String sql = "update Artigos "+
                         "set Nome = '"+nome+"', "+
                         "Preco = "+preco+", "+
                         "Quantidade = "+quantidade+" "+
                         "where Nome ='"+nomePesquisa+"';";
            
            stmt.executeUpdate(sql);

            stmt.close();
            con.close();

        } catch (SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
    }

    private void limpaCamposArtigo() {
        jTextFieldNome.setText("");
        jTextFieldPreco.setText("");
        jTextFieldQuantidade.setText("");
    }

    private void limpaCamposArtigoBD() {
        jTextFieldNome1.setText("");
        jTextFieldPreco1.setText("");
        jTextFieldQuantidade1.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppGestaoArtigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppGestaoArtigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppGestaoArtigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppGestaoArtigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppGestaoArtigos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonInserir1;
    private javax.swing.JDialog jDialogInserirArtigo;
    private javax.swing.JDialog jDialogInserirArtigoBD;
    private javax.swing.JDialog jDialogVerTudo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenuAplicacao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGestaoArtigos;
    private javax.swing.JMenuItem jMenuItemAplicacaoTerminar;
    private javax.swing.JMenuItem jMenuItemGestaoArtigosInserir;
    private javax.swing.JMenuItem jMenuItemGestaoArtigosInserirBD;
    private javax.swing.JMenuItem jMenuItemGestaoArtigosVerTodos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableArtigos;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNome1;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldPreco1;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldQuantidade1;
    // End of variables declaration//GEN-END:variables
    GestaoArtigos g = new GestaoArtigos();
    String nomePesquisa = "";
}
