/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extv;

/**
 *
 * @author Asus
 */
public class AppTv extends javax.swing.JFrame {

    /**
     * Creates new form AppTv
     */
    public AppTv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMostrador = new javax.swing.JPanel();
        jLabelCanal = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabelExtraMostradorCanal = new javax.swing.JLabel();
        jPanelControl = new javax.swing.JPanel();
        jButtonStart = new javax.swing.JButton();
        jButtonCanalMais = new javax.swing.JButton();
        jButtonCanalMenos = new javax.swing.JButton();
        jButtonVolumeMais = new javax.swing.JButton();
        jButtonVolumeMenos = new javax.swing.JButton();
        jLabelExtraControlVolume = new javax.swing.JLabel();
        jLabelExtraControlCanal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMostrador.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCanal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelCanal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCanal.setText("1");

        jLabelExtraMostradorCanal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelExtraMostradorCanal.setText("Canal");

        javax.swing.GroupLayout jPanelMostradorLayout = new javax.swing.GroupLayout(jPanelMostrador);
        jPanelMostrador.setLayout(jPanelMostradorLayout);
        jPanelMostradorLayout.setHorizontalGroup(
            jPanelMostradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostradorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMostradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMostradorLayout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMostradorLayout.createSequentialGroup()
                        .addComponent(jLabelExtraMostradorCanal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCanal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );
        jPanelMostradorLayout.setVerticalGroup(
            jPanelMostradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMostradorLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jPanelMostradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCanal)
                    .addComponent(jLabelExtraMostradorCanal))
                .addGap(44, 44, 44)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonStart.setBackground(new java.awt.Color(255, 255, 255));
        jButtonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atividade1portefolio1012527/ligar.png"))); // NOI18N
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonCanalMais.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCanalMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atividade1portefolio1012527/cima.jpg"))); // NOI18N
        jButtonCanalMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCanalMaisActionPerformed(evt);
            }
        });

        jButtonCanalMenos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCanalMenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atividade1portefolio1012527/baixo.jpg"))); // NOI18N
        jButtonCanalMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCanalMenosActionPerformed(evt);
            }
        });

        jButtonVolumeMais.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVolumeMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atividade1portefolio1012527/direita.jpg"))); // NOI18N
        jButtonVolumeMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolumeMaisActionPerformed(evt);
            }
        });

        jButtonVolumeMenos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVolumeMenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atividade1portefolio1012527/esquerda.jpg"))); // NOI18N
        jButtonVolumeMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolumeMenosActionPerformed(evt);
            }
        });

        jLabelExtraControlVolume.setText("Volume");

        jLabelExtraControlCanal.setText("Canal");

        javax.swing.GroupLayout jPanelControlLayout = new javax.swing.GroupLayout(jPanelControl);
        jPanelControl.setLayout(jPanelControlLayout);
        jPanelControlLayout.setHorizontalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVolumeMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVolumeMais))
                    .addGroup(jPanelControlLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabelExtraControlVolume)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCanalMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCanalMais, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelExtraControlCanal)
                .addGap(28, 28, 28)
                .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelControlLayout.setVerticalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addComponent(jButtonCanalMais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCanalMenos)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelControlLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonVolumeMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVolumeMais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelExtraControlVolume)))
                .addContainerGap())
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelExtraControlCanal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMostrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMostrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        if (tv.isLigado()) {
            tv.desligar();
            jPanelMostrador.setBackground(new java.awt.Color(240, 240, 240));
            jProgressBar1.setValue(0);
        } else {
            tv.ligar();
            jPanelMostrador.setBackground(new java.awt.Color(153, 204, 255));
            jProgressBar1.setValue(tv.getSom());
        }
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonCanalMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCanalMaisActionPerformed
        if (tv.isLigado()) {
            tv.canalMais();
            jLabelCanal.setText(""+tv.getCanal());
        }
        
    }//GEN-LAST:event_jButtonCanalMaisActionPerformed

    private void jButtonCanalMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCanalMenosActionPerformed
        
        if (tv.isLigado()) {
            tv.canalMenos();
            if (tv.getCanal()>0){
                jLabelCanal.setText(""+tv.getCanal());
            } else if (tv.getCanal()==0){
                jLabelCanal.setText("N");
            } else {
                jLabelCanal.setText("R");
            }
        }
    }//GEN-LAST:event_jButtonCanalMenosActionPerformed

    private void jButtonVolumeMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolumeMaisActionPerformed
        if (tv.isLigado()) {
            tv.volumeMais();
            jProgressBar1.setValue(tv.getSom()); 
        }
        
    }//GEN-LAST:event_jButtonVolumeMaisActionPerformed

    private void jButtonVolumeMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolumeMenosActionPerformed
        if (tv.isLigado()) {
            tv.volumeMenos();
            if (tv.getVolume()>0){
                jProgressBar1.setValue(tv.getSom());
            }      
        }
        
    }//GEN-LAST:event_jButtonVolumeMenosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppTv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppTv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppTv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppTv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppTv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCanalMais;
    private javax.swing.JButton jButtonCanalMenos;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonVolumeMais;
    private javax.swing.JButton jButtonVolumeMenos;
    private javax.swing.JLabel jLabelCanal;
    private javax.swing.JLabel jLabelExtraControlCanal;
    private javax.swing.JLabel jLabelExtraControlVolume;
    private javax.swing.JLabel jLabelExtraMostradorCanal;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelMostrador;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    Tv tv = new Tv();

}
