/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pratica2017;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jfig
 */
public class AppControloDespesas extends javax.swing.JFrame {

    /**
     * Creates new form AppControloDespesas
     */
    public AppControloDespesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAutor = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDialogRegistoDespesa = new javax.swing.JDialog();
        jComboBoxMeses = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTipoDespesa = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxMesDias = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonRegistar = new javax.swing.JButton();
        jDialogVerDespesas = new javax.swing.JDialog();
        jComboBoxMesesVer = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVerDespesas = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemApSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuGestaoReceitas = new javax.swing.JMenu();
        jMenuItemGestaoReceitasRegistar = new javax.swing.JMenuItem();
        jMenuItemGestaoReceitasVer = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemGestaoDespesasRegistar = new javax.swing.JMenuItem();
        jMenuItemGestaoDespesasVer = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAutor = new javax.swing.JMenuItem();

        jDialogAutor.setTitle("Autor");
        jDialogAutor.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("José Quitério");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("389");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Engenharia Informática");

        javax.swing.GroupLayout jDialogAutorLayout = new javax.swing.GroupLayout(jDialogAutor.getContentPane());
        jDialogAutor.getContentPane().setLayout(jDialogAutorLayout);
        jDialogAutorLayout.setHorizontalGroup(
            jDialogAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAutorLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jDialogAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jDialogAutorLayout.setVerticalGroup(
            jDialogAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAutorLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jDialogRegistoDespesa.setTitle("Registo Despesa");
        jDialogRegistoDespesa.setMinimumSize(new java.awt.Dimension(400, 350));
        jDialogRegistoDespesa.getContentPane().setLayout(null);

        jComboBoxMeses.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro", " " }));
        jComboBoxMeses.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxMesesPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBoxMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMesesActionPerformed(evt);
            }
        });
        jDialogRegistoDespesa.getContentPane().add(jComboBoxMeses);
        jComboBoxMeses.setBounds(42, 29, 259, 28);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Despesa"));

        jLabel4.setText("Tipo de despesa:");

        jComboBoxTipoDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTipoDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDespesaActionPerformed(evt);
            }
        });

        jLabel5.setText("Dia:");

        jComboBoxMesDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMesDiasActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor:");

        jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("€");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTipoDespesa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxMesDias, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxTipoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxMesDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27))
        );

        jDialogRegistoDespesa.getContentPane().add(jPanel1);
        jPanel1.setBounds(42, 75, 259, 142);

        jButtonRegistar.setText("Registar");
        jButtonRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistarActionPerformed(evt);
            }
        });
        jDialogRegistoDespesa.getContentPane().add(jButtonRegistar);
        jButtonRegistar.setBounds(216, 247, 85, 23);

        jDialogVerDespesas.setTitle("Ver Despesas");
        jDialogVerDespesas.setMinimumSize(new java.awt.Dimension(400, 300));

        jComboBoxMesesVer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxMesesVer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro", " " }));
        jComboBoxMesesVer.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxMesesVerPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jTableVerDespesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Tipo Despesa", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableVerDespesas);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total: ");

        jLabelTotal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotal.setText("0");
        jLabelTotal.setOpaque(true);

        javax.swing.GroupLayout jDialogVerDespesasLayout = new javax.swing.GroupLayout(jDialogVerDespesas.getContentPane());
        jDialogVerDespesas.getContentPane().setLayout(jDialogVerDespesasLayout);
        jDialogVerDespesasLayout.setHorizontalGroup(
            jDialogVerDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerDespesasLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jDialogVerDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jComboBoxMesesVer, 0, 319, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogVerDespesasLayout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jDialogVerDespesasLayout.setVerticalGroup(
            jDialogVerDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerDespesasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jComboBoxMesesVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jDialogVerDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelTotal))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Aplicação");

        jMenuItemApSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemApSair.setText("Sair");
        jMenuItemApSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemApSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gestão");

        jMenuGestaoReceitas.setText("Receitas");

        jMenuItemGestaoReceitasRegistar.setText("Registar");
        jMenuGestaoReceitas.add(jMenuItemGestaoReceitasRegistar);

        jMenuItemGestaoReceitasVer.setText("Ver");
        jMenuGestaoReceitas.add(jMenuItemGestaoReceitasVer);

        jMenu2.add(jMenuGestaoReceitas);

        jMenu4.setText("Despesas");

        jMenuItemGestaoDespesasRegistar.setText("Registar");
        jMenuItemGestaoDespesasRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestaoDespesasRegistarActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemGestaoDespesasRegistar);

        jMenuItemGestaoDespesasVer.setText("Ver");
        jMenuItemGestaoDespesasVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestaoDespesasVerActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemGestaoDespesasVer);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        jMenuItemAutor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAutor.setText("Autor");
        jMenuItemAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAutorActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAutor);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemApSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemApSairActionPerformed

    private void jMenuItemGestaoDespesasRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestaoDespesasRegistarActionPerformed
       lerTiposDespesa();
       jDialogRegistoDespesa.setVisible(true);
    }//GEN-LAST:event_jMenuItemGestaoDespesasRegistarActionPerformed

    private void jMenuItemAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAutorActionPerformed
        jDialogAutor.setVisible(true);
    }//GEN-LAST:event_jMenuItemAutorActionPerformed

    private void jComboBoxMesesPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxMesesPopupMenuWillBecomeInvisible
        int mes = jComboBoxMeses.getSelectedIndex();
        jComboBoxMesDias.removeAllItems();
        for (int i=1;i<=diasMes(mes);i++){
            jComboBoxMesDias.addItem(""+i);
        }
    }//GEN-LAST:event_jComboBoxMesesPopupMenuWillBecomeInvisible

    private void jButtonRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarActionPerformed
        int mes = jComboBoxMeses.getSelectedIndex()+1;
        String tipoDespesa = jComboBoxTipoDespesa.getSelectedItem().toString();
        int dia = jComboBoxMesDias.getSelectedIndex()+1;
        double valor = Double.parseDouble(jTextFieldValor.getText());
        
        inserirRegisto(mes, tipoDespesa, dia, valor);
    }//GEN-LAST:event_jButtonRegistarActionPerformed

    private void jComboBoxMesesVerPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxMesesVerPopupMenuWillBecomeInvisible
        int mes = jComboBoxMesesVer.getSelectedIndex()+1;
        lerDespesasPorMes(mes);
    }//GEN-LAST:event_jComboBoxMesesVerPopupMenuWillBecomeInvisible

    private void jMenuItemGestaoDespesasVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestaoDespesasVerActionPerformed
        jDialogVerDespesas.setVisible(true);
    }//GEN-LAST:event_jMenuItemGestaoDespesasVerActionPerformed

    private void jComboBoxMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMesesActionPerformed

    private void jComboBoxMesDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMesDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMesDiasActionPerformed

    private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorActionPerformed

    private void jComboBoxTipoDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoDespesaActionPerformed

    private void lerDespesasPorMes(int mes){
        String url = "jdbc:sqlite:BDReceitasDespesas";
        Connection con;
        Statement stmt;
        DefaultTableModel modelo = (DefaultTableModel)jTableVerDespesas.getModel();
        modelo.setRowCount(0);
        try {
            Class.forName("org.sqlite.JDBC");
        } catch(java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }
        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from RegistoDespesa where mes = "+mes );
            double total = 0;
            while (rs.next()) {	
            		int dia = rs.getInt("Dia");
                        String tipo = rs.getString("TipoDespesa");
                        double valor = rs.getDouble("Valor");
                        total = total + valor;
                        Object rowData[] = {dia,tipo,valor};
                        modelo.addRow(rowData);
	    }
            jLabelTotal.setText(""+total);
            stmt.close();
            con.close();
        } catch(SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
        
    }
    
    private void inserirRegisto(int mes,String tipo, int dia, double valor){
        String url = "jdbc:sqlite:BDReceitasDespesas";
        Connection con;
        Statement stmt;

        try {
            Class.forName("org.sqlite.JDBC");
        } catch(java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }

        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            stmt.executeUpdate("INSERT INTO RegistoDespesa " +
            	 "VALUES ("+mes+",'"+tipo+"',"+dia+","+valor+")");
        	 
            stmt.close();
            con.close();
            

        } catch(SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
        
    }
    
    private int diasMes(int mes){
        int m[] = {31,29,31,30,31,30,31,31,30,31,30,31};
        return m[mes];
    }
    
    private void lerTiposDespesa(){
        String url = "jdbc:sqlite:BDReceitasDespesas";
        Connection con;
        Statement stmt;
        jComboBoxTipoDespesa.removeAllItems();
        try {
            Class.forName("org.sqlite.JDBC");
        } catch(java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }
        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from TipoDespesa");
            jComboBoxTipoDespesa.addItem("-- Escolha o Tipo de Despesa --");
            while (rs.next()) {	
            		String tipo = rs.getString("Tipo");
                        jComboBoxTipoDespesa.addItem(tipo);
	    }
            stmt.close();
            con.close();
        } catch(SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppControloDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppControloDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppControloDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppControloDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppControloDespesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistar;
    private javax.swing.JComboBox<String> jComboBoxMesDias;
    private javax.swing.JComboBox<String> jComboBoxMeses;
    private javax.swing.JComboBox<String> jComboBoxMesesVer;
    private javax.swing.JComboBox<String> jComboBoxTipoDespesa;
    private javax.swing.JDialog jDialogAutor;
    private javax.swing.JDialog jDialogRegistoDespesa;
    private javax.swing.JDialog jDialogVerDespesas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGestaoReceitas;
    private javax.swing.JMenuItem jMenuItemApSair;
    private javax.swing.JMenuItem jMenuItemAutor;
    private javax.swing.JMenuItem jMenuItemGestaoDespesasRegistar;
    private javax.swing.JMenuItem jMenuItemGestaoDespesasVer;
    private javax.swing.JMenuItem jMenuItemGestaoReceitasRegistar;
    private javax.swing.JMenuItem jMenuItemGestaoReceitasVer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVerDespesas;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
