/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividadeperguntas;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Asus
 */
public class AppQuestionario extends javax.swing.JFrame {

    /**
     * Creates new form AppPerguntas
     */
    public AppQuestionario() {
        initComponents();
        lerTemasToComboBox();
        criarTimer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBoxTemas = new javax.swing.JComboBox<>();
        jButtonIniciar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelPergunta = new javax.swing.JLabel();
        jRadioButtonR1 = new javax.swing.JRadioButton();
        jRadioButtonR2 = new javax.swing.JRadioButton();
        jRadioButtonR3 = new javax.swing.JRadioButton();
        jRadioButtonR4 = new javax.swing.JRadioButton();
        jButtonNext = new javax.swing.JButton();
        jLabelTimer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jComboBoxTemas.setBackground(new java.awt.Color(0, 51, 153));
        jComboBoxTemas.setForeground(new java.awt.Color(255, 255, 0));
        jComboBoxTemas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Musica", "Desporto" }));
        jComboBoxTemas.setToolTipText("");

        jButtonIniciar.setBackground(new java.awt.Color(0, 51, 153));
        jButtonIniciar.setForeground(new java.awt.Color(255, 255, 0));
        jButtonIniciar.setText("Jogar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jButtonSair.setBackground(new java.awt.Color(0, 51, 153));
        jButtonSair.setForeground(new java.awt.Color(255, 255, 0));
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabelPergunta.setBackground(new java.awt.Color(0, 51, 153));
        jLabelPergunta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPergunta.setForeground(new java.awt.Color(255, 255, 51));
        jLabelPergunta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 204)));

        jRadioButtonR1.setBackground(new java.awt.Color(0, 51, 153));
        jRadioButtonR1.setForeground(new java.awt.Color(255, 255, 0));
        jRadioButtonR1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 204)));
        jRadioButtonR1.setBorderPainted(true);
        jRadioButtonR1.setOpaque(false);

        jRadioButtonR2.setBackground(new java.awt.Color(0, 51, 153));
        jRadioButtonR2.setForeground(new java.awt.Color(255, 255, 0));
        jRadioButtonR2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 204)));
        jRadioButtonR2.setBorderPainted(true);
        jRadioButtonR2.setOpaque(false);

        jRadioButtonR3.setBackground(new java.awt.Color(0, 51, 153));
        jRadioButtonR3.setForeground(new java.awt.Color(255, 255, 0));
        jRadioButtonR3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 204)));
        jRadioButtonR3.setBorderPainted(true);
        jRadioButtonR3.setOpaque(false);

        jRadioButtonR4.setBackground(new java.awt.Color(0, 51, 153));
        jRadioButtonR4.setForeground(new java.awt.Color(255, 255, 0));
        jRadioButtonR4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 204)));
        jRadioButtonR4.setBorderPainted(true);
        jRadioButtonR4.setOpaque(false);

        jButtonNext.setBackground(new java.awt.Color(0, 0, 204));
        jButtonNext.setForeground(new java.awt.Color(255, 255, 51));
        jButtonNext.setText("Próxima pergunta");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jLabelTimer.setForeground(new java.awt.Color(255, 255, 0));
        jLabelTimer.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jRadioButtonR3, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(jRadioButtonR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonR2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(jRadioButtonR4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNext)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonIniciar)
                            .addComponent(jButtonSair)
                            .addComponent(jComboBoxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonR1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonR2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonR3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonR4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNext)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        questoes.clear();
        nP = 0;
        String tema = jComboBoxTemas.getSelectedItem().toString();
        if (jComboBoxTemas.getSelectedIndex() > 0) lerPerguntasPorTema(tema);
        escrevePergunta(0);
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        if (nP < questoes.size()-1){
            nP++;
            escrevePergunta(nP);
            
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void escrevePergunta(int nP){
        timer1.start();
        Questionario q = questoes.get(nP);
        jLabelPergunta.setText(q.getPergunta());
        jRadioButtonR1.setText(q.getRespostaNumero(0));
        jRadioButtonR2.setText(q.getRespostaNumero(1));
        jRadioButtonR3.setText(q.getRespostaNumero(2));
        jRadioButtonR4.setText(q.getRespostaNumero(3));
        
        
    }
    
    private void lerPerguntasPorTema(String tema){
        String sqlQuery1 = "select Pergunta.idPergunta, Pergunta.Pergunta " +
                          "from Pergunta " +
                          "where Pergunta.Tema = '"+tema+"'";

        try {
            Connection connection = null;
            ResultSet resultSet = null;
            Statement statement = null;

            Class.forName("org.sqlite.JDBC");
            connection = DriverManager.getConnection("jdbc:sqlite:BDQuestoes.db");
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sqlQuery1);
            
            // Ler perguntas do tema
            while (resultSet.next()) {
                String pergunta = resultSet.getString("Pergunta");
                int idPergunta = resultSet.getInt("idPergunta");
                questoes.add(new Questionario(idPergunta, pergunta, tema));
            }

            // Ler Respostas para cada pergunta
            
            for (Questionario q : questoes){
                ArrayList<Resposta> r= new ArrayList<>();
                String sqlQuery2 = "select Resposta.Resposta, Resposta.Classificacao "+
                               "from Resposta "+
                               "where Resposta.idPergunta = "+q.getIdPergunta();
                resultSet = statement.executeQuery(sqlQuery2);
                
                while (resultSet.next()) {
                    String resposta = resultSet.getString("Resposta");
                    int valor = resultSet.getInt("Classificacao");
                    System.out.println("Resposta "+ resposta+ " valor: "+valor);
                    jLabel1.setText("Pontuação :" + valor);
                    r.add(new Resposta(resposta, valor));
                    
                }
                q.setRespostas(r);
                
            }
            
            this.endDate = LocalDateTime.now().plusSeconds(200);
            
            resultSet.close();
            statement.close();
            connection.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AppQuestionario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AppQuestionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void lerTemasToComboBox() {
        try {
            Connection connection = null;
            ResultSet resultSet = null;
            Statement statement = null;

            Class.forName("org.sqlite.JDBC");
            connection = DriverManager.getConnection("jdbc:sqlite:BDQuestoes.db");
            statement = connection.createStatement();
            resultSet = statement.executeQuery("select distinct Tema from Pergunta");
            jComboBoxTemas.removeAllItems();
            jComboBoxTemas.addItem("--- Escolha um Tema ---");
            while (resultSet.next()) {
               String tema = resultSet.getString("Tema");
               jComboBoxTemas.addItem(tema);
            }
            
            
            
            resultSet.close();
            statement.close();
            connection.close();
          
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AppQuestionario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AppQuestionario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    private void criarTimer(){
        timer1 = new javax.swing.Timer(1000, (ActionEvent e) -> {
            if(this.endDate != null) {
                LocalDateTime startDate = LocalDateTime.now();
                long missing = startDate.until(this.endDate, ChronoUnit.SECONDS);
                jLabelTimer.setText(""+missing);
                
                
                if(missing == 0) {
                    this.endDate = null;
                    jLabelTimer.setText("Perdeu");
                    JOptionPane.showMessageDialog(null, "Excedeu o tempo!!! Perdeu");
                    System.exit(0);
                    
                }}
        });
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppQuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox<String> jComboBoxTemas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPergunta;
    private javax.swing.JLabel jLabelTimer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonR1;
    private javax.swing.JRadioButton jRadioButtonR2;
    private javax.swing.JRadioButton jRadioButtonR3;
    private javax.swing.JRadioButton jRadioButtonR4;
    // End of variables declaration//GEN-END:variables
    ArrayList<Questionario> questoes = new ArrayList<>();
    int nP = 0;
    Timer timer1;
    LocalDateTime endDate;
}
