/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projquestionario;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Quitério
 */
public class AppQuestionario extends javax.swing.JFrame {

    /**
     * Creates new form AppQuestionario
     */
    public AppQuestionario() {
        initComponents();
        lerTemasToComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTema = new javax.swing.JPanel();
        jComboBoxTemas = new javax.swing.JComboBox<>();
        jButtonIniciar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelPergunta = new javax.swing.JLabel();
        jRadioButtonR1 = new javax.swing.JRadioButton();
        jRadioButtonR2 = new javax.swing.JRadioButton();
        jRadioButtonR3 = new javax.swing.JRadioButton();
        jRadioButtonR4 = new javax.swing.JRadioButton();
        jButtonNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Questionário");

        jPanelTema.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jComboBoxTemas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Escolha o Tema --" }));

        javax.swing.GroupLayout jPanelTemaLayout = new javax.swing.GroupLayout(jPanelTema);
        jPanelTema.setLayout(jPanelTemaLayout);
        jPanelTemaLayout.setHorizontalGroup(
            jPanelTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTemaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jComboBoxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTemaLayout.setVerticalGroup(
            jPanelTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabelPergunta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPergunta.setText("Pergunta");
        jPanel1.add(jLabelPergunta);
        jLabelPergunta.setBounds(10, 11, 441, 17);

        jRadioButtonR1.setText("Resposta 1");
        jPanel1.add(jRadioButtonR1);
        jRadioButtonR1.setBounds(40, 40, 406, 23);

        jRadioButtonR2.setText("Resposta 1");
        jPanel1.add(jRadioButtonR2);
        jRadioButtonR2.setBounds(40, 70, 406, 23);

        jRadioButtonR3.setText("Resposta 1");
        jPanel1.add(jRadioButtonR3);
        jRadioButtonR3.setBounds(40, 130, 406, 23);

        jRadioButtonR4.setText("Resposta 1");
        jPanel1.add(jRadioButtonR4);
        jRadioButtonR4.setBounds(40, 100, 406, 23);

        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButtonIniciar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonIniciar)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        questoes.clear();
        nP = 0;
        String tema = jComboBoxTemas.getSelectedItem().toString();
        if (jComboBoxTemas.getSelectedIndex() > 0) lerPerguntasPorTema(tema);
        escrevePergunta(0);
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        if (nP < questoes.size()-1){
            nP++;
            escrevePergunta(nP);
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void escrevePergunta(int nP){
        Questionario q = questoes.get(nP);
        jLabelPergunta.setText(q.getPergunta());
        jRadioButtonR1.setText(q.getRespostaNumero(0));
        jRadioButtonR2.setText(q.getRespostaNumero(1));
        jRadioButtonR3.setText(q.getRespostaNumero(2));
        jRadioButtonR4.setText(q.getRespostaNumero(3));
    }
    
    private void lerPerguntasPorTema(String tema){
        String sqlQuery1 = "select Pergunta.idPergunta, Pergunta.Pergunta " +
                          "from Pergunta " +
                          "where Pergunta.Tema = '"+tema+"'";
//        String sqlQuery2 = "select Pergunta.Pergunta, Resposta.Resposta, Resposta.Classificacao " +
//                          "from Pergunta " +
//                          "INNER JOIN Resposta ON Pergunta.idPergunta = Resposta.idPergunta "+
//                          "where Pergunta.Tema = '"+tema+"'";
        try {
            Connection connection = null;
            ResultSet resultSet = null;
            Statement statement = null;

            Class.forName("org.sqlite.JDBC");
            connection = DriverManager.getConnection("jdbc:sqlite:BDQuestionario.db");
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sqlQuery1);
            
            // Ler perguntas do tema
            while (resultSet.next()) {
                String pergunta = resultSet.getString("Pergunta");
                int idPergunta = resultSet.getInt("idPergunta");
                questoes.add(new Questionario(idPergunta, pergunta, tema));
            }

            // Ler Respostas para cada pergunta
            
            for (Questionario q : questoes){
                ArrayList<Resposta> r= new ArrayList<>();
                String sqlQuery2 = "select Resposta.Resposta, Resposta.Classificacao "+
                               "from Resposta "+
                               "where Resposta.idPergunta = "+q.getIdPergunta();
                resultSet = statement.executeQuery(sqlQuery2);
                while (resultSet.next()) {
                    String resposta = resultSet.getString("Resposta");
                    int valor = resultSet.getInt("Classificacao");
                    System.out.println("Resposta "+ resposta+ " valor: "+valor);
                    r.add(new Resposta(resposta, valor));
                }
                q.setRespostas(r);
            }
            
            resultSet.close();
            statement.close();
            connection.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AppQuestionario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AppQuestionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void lerTemasToComboBox() {
        try {
            Connection connection = null;
            ResultSet resultSet = null;
            Statement statement = null;

            Class.forName("org.sqlite.JDBC");
            connection = DriverManager.getConnection("jdbc:sqlite:BDQuestionario.db");
            statement = connection.createStatement();
            resultSet = statement.executeQuery("select distinct Tema from Pergunta");
            jComboBoxTemas.removeAllItems();
            jComboBoxTemas.addItem("-- Escolha o Tema --");
            while (resultSet.next()) {
               String tema = resultSet.getString("Tema");
               jComboBoxTemas.addItem(tema);
            }

            resultSet.close();
            statement.close();
            connection.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AppQuestionario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AppQuestionario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppQuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JComboBox<String> jComboBoxTemas;
    private javax.swing.JLabel jLabelPergunta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTema;
    private javax.swing.JRadioButton jRadioButtonR1;
    private javax.swing.JRadioButton jRadioButtonR2;
    private javax.swing.JRadioButton jRadioButtonR3;
    private javax.swing.JRadioButton jRadioButtonR4;
    // End of variables declaration//GEN-END:variables
    ArrayList<Questionario> questoes = new ArrayList<>();
    int nP = 0;
}
