/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package outros;

import java.io.File;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
import java.util.Set;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jfig
 */
public class AppEuroMilhoes extends javax.swing.JFrame {

    /**
     * Creates new form AppEuroMilhoes
     */
    public AppEuroMilhoes() {
        initComponents();
        desenharNumeros();
    }

    private void desenharNumeros() {
        int posInicialX = 5, posInicialY = 5, tamanhoX = 18, tamanhoY = 16;
        int posX = posInicialX, posY = posInicialY;
        int espaco = 3;

        for (int i = 1; i <= 50; i++) {
            javax.swing.JLabel jLabel = new javax.swing.JLabel();
            jLabel.setBackground(new java.awt.Color(255, 255, 255));
            if (aposta.contains(i)){
                jLabel.setBackground(new java.awt.Color(0, 255, 51));
            }
            jLabel.setText(String.format("%2d", i));
            jLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            jLabel.setOpaque(true);
            jLabel.setBounds(posX, posY, tamanhoX, tamanhoY);
            posX = posX + tamanhoX + espaco;
            if (i % 6 == 0) {
                posX = posInicialX;
                posY = posY + tamanhoY + espaco;
            }

            jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    int valor = Integer.parseInt(jLabel.getText().trim());
                    if (aposta.size() < 5) {
                        if (!aposta.add(valor)) {
                            jLabel.setBackground(new java.awt.Color(255, 255, 255));
                            aposta.remove(valor);
                        } else {
                            jLabel.setBackground(new java.awt.Color(0, 255, 51));
                        }
                    } else if (aposta.size() == 5) {
                        aposta.remove(valor);
                        jLabel.setBackground(new java.awt.Color(255, 255, 255));
                    }
                }
            }
            );

            jPanel1.add(jLabel);
        }
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jDialogVerificarPremio = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelChave = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableResultados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaApostas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonApostar = new javax.swing.JButton();
        jButtonGerarNumeros = new javax.swing.JButton();
        jButtonRegistarApostas = new javax.swing.JButton();
        jButtonVerificarApostas = new javax.swing.JButton();

        jDialogVerificarPremio.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Chave:");

        jLabelChave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelChave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelChave.setText("jLabel3");

        jTableResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apostas", "Resultados", "Prémio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableResultados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelChave, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelChave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialogVerificarPremioLayout = new javax.swing.GroupLayout(jDialogVerificarPremio.getContentPane());
        jDialogVerificarPremio.getContentPane().setLayout(jDialogVerificarPremioLayout);
        jDialogVerificarPremioLayout.setHorizontalGroup(
            jDialogVerificarPremioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogVerificarPremioLayout.setVerticalGroup(
            jDialogVerificarPremioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogar EuroMilhões");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );

        jTextAreaApostas.setColumns(20);
        jTextAreaApostas.setRows(5);
        jScrollPane1.setViewportView(jTextAreaApostas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Apostas");

        jButtonApostar.setText("Apostar");
        jButtonApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApostarActionPerformed(evt);
            }
        });

        jButtonGerarNumeros.setText("Gerar Números");
        jButtonGerarNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarNumerosActionPerformed(evt);
            }
        });

        jButtonRegistarApostas.setText("Registar Apostas");
        jButtonRegistarApostas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistarApostasActionPerformed(evt);
            }
        });

        jButtonVerificarApostas.setText("Verificar Apostas");
        jButtonVerificarApostas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificarApostasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGerarNumeros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRegistarApostas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVerificarApostas)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonApostar)
                    .addComponent(jButtonGerarNumeros)
                    .addComponent(jButtonRegistarApostas)
                    .addComponent(jButtonVerificarApostas))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApostarActionPerformed
        if (aposta.size() == 5) {
            jTextAreaApostas.append("" + aposta + "\n");
            aposta.clear();
            jPanel1.removeAll();
            desenharNumeros();
        } else {
            JOptionPane.showMessageDialog(this, "São necessários CINCO números!");
        }

    }//GEN-LAST:event_jButtonApostarActionPerformed

    private void jButtonGerarNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarNumerosActionPerformed
        aposta = gerarNumeros(1, 50, 5);
        jPanel1.removeAll();
        desenharNumeros();
    }//GEN-LAST:event_jButtonGerarNumerosActionPerformed

    private void jButtonRegistarApostasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarApostasActionPerformed
              
        try {
            escreverFicheiroTxt(LocalDate.now()+"");
        } catch (IOException ex) {
            Logger.getLogger(AppEuroMilhoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonRegistarApostasActionPerformed

    private void jButtonVerificarApostasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificarApostasActionPerformed
        jFileChooser1.setCurrentDirectory(new File(Paths.get(".").toAbsolutePath().normalize().toString()));
        jFileChooser1.addChoosableFileFilter(new FileFilter() {
        @Override
        public boolean accept(File f) {
            if (f.isDirectory()) {
                return true;
            } else {
                return f.getName().toLowerCase().endsWith(".txt");
            }
        }
        
        @Override
        public String getDescription() {
            return "TXT Documents (*.txt)";
        }
    });
    jFileChooser1.showDialog(this, "Abrir");
    if(jFileChooser1.getApproveButtonText().equals("Abrir")) {
    File file = jFileChooser1.getSelectedFile();
    String nomeFicheiro = file.getAbsolutePath(); 
    //System.out.println("Nome: "+nomeFicheiro);
        try {
            lerFicheiro(nomeFicheiro);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AppEuroMilhoes.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }

    Set<Integer> chave = gerarNumeros(1, 50, 5);
    jLabelChave.setText(chave.toString());
    
    DefaultTableModel modelo = (DefaultTableModel)jTableResultados.getModel();
    modelo.setRowCount(0);
    Set<Integer> intersecao = chave;
    for (String s :tJogo){
        String col1 = s;
        Set<Integer> ap = StringToSet(s);
        ap.retainAll(intersecao);
        String col2 = ap.toString();
        String col3 = verPremio(ap.size())+"";
        Object []rowData= {col1,col2,col3};
        modelo.addRow(rowData);       
    }
    
    jDialogVerificarPremio.setVisible(true);
            
    }//GEN-LAST:event_jButtonVerificarApostasActionPerformed

    private int verPremio(int valor){
        int v[] = {0,5,4,3,2,1};
        if ((valor>=0)||(valor<=5)){
            return v[valor];
        }
        return 0;
    }
    
    private Set<Integer> StringToSet(String s){
        Set<Integer> c = new TreeSet<>();
        Scanner ler = new Scanner (s).useDelimiter("\\D");
        int n = 0;
        int n1=0;
        while(n<5){
            if(ler.hasNextInt()){
                n1 = ler.nextInt();
                n++;
                c.add(n1);
            }else {
                ler.next();
            }
        }
        return c;
    }
    
    private void lerFicheiro(String ficheiro) throws FileNotFoundException {
        Scanner fileScanner = new Scanner (new File(ficheiro));
        tJogo.clear();
        Set<Integer> jogo = new TreeSet<>();
        while (fileScanner.hasNextInt()) {
            jogo.clear();
            for (int j = 0; j < 5; j++) {
                int i = fileScanner.nextInt();
                jogo.add(i);
            }
            tJogo.add(jogo.toString());
        }
    }
    
    
    private void escreverFicheiroTxt(String nome) throws IOException {
        
            FileWriter arq = new FileWriter(nome+".txt");
            PrintWriter gravarArq = new PrintWriter(arq);
             gravarArq.printf("%s", jTextAreaApostas.getText());
//            int pos = 0;
//            int tamanho = 20;
//            System.out.println("Total: "+jTextAreaApostas.getText().length());
//            do {
//                gravarArq.printf("%s\n", jTextAreaApostas.getText(pos, tamanho));
//                pos = pos + tamanho;
//            } while (pos<jTextAreaApostas.getText().length());
            arq.close();
        
    }
    
    private Set<Integer> gerarNumeros(int min, int max, int n) {
        Set<Integer> v = new TreeSet<>();
        Random random = new Random();
        int i = 0;
        
        do{ 
            int valor = random.nextInt((max - min) + 1) + min;
            if (v.add(valor)){
                i++;
            }
        }while(i < n);
        return v;
    }
    
    private void gerarNumerosArray(int min, int max, int n) {
        int v[] = new int[5];
        Random random = new Random();
        int i = 0;
        
        do{ 
            boolean existe = false;
            int valor = random.nextInt((max - min) + 1) + min;
            for (int j=0;j<v.length;j++){
                if (valor == v[j]){
                    existe = true;
                    break;
                }
            }
            if (!existe){
                v[i]= valor;
                System.out.println("v["+i+"]="+v[i]);
                i++;
            }
                
        }while(i < n);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppEuroMilhoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppEuroMilhoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppEuroMilhoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppEuroMilhoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppEuroMilhoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApostar;
    private javax.swing.JButton jButtonGerarNumeros;
    private javax.swing.JButton jButtonRegistarApostas;
    private javax.swing.JButton jButtonVerificarApostas;
    private javax.swing.JDialog jDialogVerificarPremio;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelChave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableResultados;
    private javax.swing.JTextArea jTextAreaApostas;
    // End of variables declaration//GEN-END:variables
    Set<Integer> aposta = new TreeSet<Integer>();
    ArrayList<String> tJogo = new ArrayList<>();
}
