/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exauto;

/**
 *
 * @author jfig
 */
public class AppAuto extends javax.swing.JFrame {

    /**
     * Creates new form AppAuto
     */
    public AppAuto() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMostrador = new javax.swing.JPanel();
        jLabelVelocidade = new javax.swing.JLabel();
        jLabelMudanca = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanelControl = new javax.swing.JPanel();
        jButtonStart = new javax.swing.JButton();
        jButtonAcelerar = new javax.swing.JButton();
        jButtonTravar = new javax.swing.JButton();
        jButtonMudancaMais = new javax.swing.JButton();
        jButtonMudancaMenos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMostrador.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelVelocidade.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelVelocidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVelocidade.setText("0");
        jLabelVelocidade.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelMudanca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelMudanca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMudanca.setText("0");
        jLabelMudanca.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jProgressBar1.setOrientation(1);
        jProgressBar1.setToolTipText("");

        javax.swing.GroupLayout jPanelMostradorLayout = new javax.swing.GroupLayout(jPanelMostrador);
        jPanelMostrador.setLayout(jPanelMostradorLayout);
        jPanelMostradorLayout.setHorizontalGroup(
            jPanelMostradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostradorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelMudanca, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabelVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMostradorLayout.setVerticalGroup(
            jPanelMostradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostradorLayout.createSequentialGroup()
                .addGroup(jPanelMostradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMostradorLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelMostradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMudanca, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelMostradorLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButtonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/onOff.png"))); // NOI18N
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonAcelerar.setText("Acelerar");
        jButtonAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcelerarActionPerformed(evt);
            }
        });

        jButtonTravar.setText("Travar");
        jButtonTravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTravarActionPerformed(evt);
            }
        });

        jButtonMudancaMais.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonMudancaMais.setText("+");
        jButtonMudancaMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMudancaMaisActionPerformed(evt);
            }
        });

        jButtonMudancaMenos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonMudancaMenos.setText("-");
        jButtonMudancaMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMudancaMenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelControlLayout = new javax.swing.GroupLayout(jPanelControl);
        jPanelControl.setLayout(jPanelControlLayout);
        jPanelControlLayout.setHorizontalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMudancaMais, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMudancaMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAcelerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonStart)
                .addContainerGap())
        );
        jPanelControlLayout.setVerticalGroup(
            jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAcelerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonMudancaMais, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMudancaMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMostrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelControl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMostrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        if (auto.isLigado()) {
            auto.desligar();
            jPanelMostrador.setBackground(new java.awt.Color(240, 240, 240));
            jProgressBar1.setValue(0);
        } else {
            auto.ligar();
            jPanelMostrador.setBackground(new java.awt.Color(153, 204, 255));
            jProgressBar1.setValue(auto.getCombustivel());
        }
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonMudancaMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMudancaMaisActionPerformed
        auto.mudancaMais();
        jLabelMudanca.setText(""+auto.getMudanca());
    }//GEN-LAST:event_jButtonMudancaMaisActionPerformed

    private void jButtonMudancaMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMudancaMenosActionPerformed
        auto.mudancaMenos();
        if (auto.getMudanca()>0){
            jLabelMudanca.setText(""+auto.getMudanca());
        } else if (auto.getMudanca()==0){
            jLabelMudanca.setText("N");
        } else {
            jLabelMudanca.setText("R");
        }
    }//GEN-LAST:event_jButtonMudancaMenosActionPerformed

    private void jButtonAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcelerarActionPerformed
        auto.acelerar();
        jLabelVelocidade.setText(""+auto.getVelocidade());
        jProgressBar1.setValue(auto.getCombustivel());
    }//GEN-LAST:event_jButtonAcelerarActionPerformed

    private void jButtonTravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTravarActionPerformed
        auto.travar();
        jLabelVelocidade.setText(""+auto.getVelocidade());
    }//GEN-LAST:event_jButtonTravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppAuto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcelerar;
    private javax.swing.JButton jButtonMudancaMais;
    private javax.swing.JButton jButtonMudancaMenos;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonTravar;
    private javax.swing.JLabel jLabelMudanca;
    private javax.swing.JLabel jLabelVelocidade;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelMostrador;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    Auto auto = new Auto(75);

}
