/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividade05;

/**
 *
 * @author Asus
 */
public class FotoGrupo extends javax.swing.JFrame {

    /**
     * Creates new form FotoGrupo
     */
    public FotoGrupo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialogFoto = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabelArtista2 = new javax.swing.JLabel();
        jLabelColegial2 = new javax.swing.JLabel();
        jLabelJardineira2 = new javax.swing.JLabel();
        jLabelSurfista2 = new javax.swing.JLabel();
        jLabelTenista2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelArtista = new javax.swing.JLabel();
        jCheckBoxArtista = new javax.swing.JCheckBox();
        jLabelColegial = new javax.swing.JLabel();
        jCheckBoxColegial = new javax.swing.JCheckBox();
        jLabelJardineira = new javax.swing.JLabel();
        jCheckBoxJardineira = new javax.swing.JCheckBox();
        jLabelSurfista = new javax.swing.JLabel();
        jCheckBoxSurfista = new javax.swing.JCheckBox();
        jLabelTenista = new javax.swing.JLabel();
        jCheckBoxTenista = new javax.swing.JCheckBox();
        jCheckBoxTodas = new javax.swing.JCheckBox();
        jCheckBoxNenhuma = new javax.swing.JCheckBox();
        jButtonFoto = new javax.swing.JButton();

        jDialogFoto.setMinimumSize(new java.awt.Dimension(570, 380));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabelArtista2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Atividade05\\src\\imagensGirls\\artista.jpg")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 2, 0, 0);
        jPanel3.add(jLabelArtista2, gridBagConstraints);

        jLabelColegial2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Atividade05\\src\\imagensGirls\\colegial.jpg")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -12;
        gridBagConstraints.ipady = -14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 10, 108, 0);
        jPanel3.add(jLabelColegial2, gridBagConstraints);

        jLabelJardineira2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Atividade05\\src\\imagensGirls\\jardineira.gif")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 10, 108, 0);
        jPanel3.add(jLabelJardineira2, gridBagConstraints);

        jLabelSurfista2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Atividade05\\src\\imagensGirls\\surfista.jpg")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = -14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 6, 108, 0);
        jPanel3.add(jLabelSurfista2, gridBagConstraints);

        jLabelTenista2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Atividade05\\src\\imagensGirls\\tenista.jpg")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = -15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 6, 108, 12);
        jPanel3.add(jLabelTenista2, gridBagConstraints);

        javax.swing.GroupLayout jDialogFotoLayout = new javax.swing.GroupLayout(jDialogFoto.getContentPane());
        jDialogFoto.getContentPane().setLayout(jDialogFotoLayout);
        jDialogFotoLayout.setHorizontalGroup(
            jDialogFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogFotoLayout.setVerticalGroup(
            jDialogFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelArtista.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Atividade05\\src\\imagensGirls\\artista.jpg")); // NOI18N

        jCheckBoxArtista.setText("Artista");

        jLabelColegial.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Atividade05\\src\\imagensGirls\\colegial.jpg")); // NOI18N

        jCheckBoxColegial.setText("Colegial");

        jLabelJardineira.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Atividade05\\src\\imagensGirls\\jardineira.gif")); // NOI18N

        jCheckBoxJardineira.setText("Jardineira");

        jLabelSurfista.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Atividade05\\src\\imagensGirls\\surfista.jpg")); // NOI18N

        jCheckBoxSurfista.setText("Surfista");

        jLabelTenista.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Atividade05\\src\\imagensGirls\\tenista.jpg")); // NOI18N

        jCheckBoxTenista.setText("Tenista");

        buttonGroup1.add(jCheckBoxTodas);
        jCheckBoxTodas.setText("Todas");
        jCheckBoxTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTodasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBoxNenhuma);
        jCheckBoxNenhuma.setText("Nenhuma");
        jCheckBoxNenhuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNenhumaActionPerformed(evt);
            }
        });

        jButtonFoto.setText("FOTO");
        jButtonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jCheckBoxTodas)
                        .addGap(22, 22, 22)
                        .addComponent(jButtonFoto)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxNenhuma))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelArtista)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jCheckBoxArtista)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelColegial, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxColegial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxJardineira)
                            .addComponent(jLabelJardineira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSurfista)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jCheckBoxSurfista)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jCheckBoxTenista)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelTenista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelJardineira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelColegial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addComponent(jLabelSurfista, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTenista, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxColegial)
                    .addComponent(jCheckBoxArtista)
                    .addComponent(jCheckBoxJardineira)
                    .addComponent(jCheckBoxSurfista)
                    .addComponent(jCheckBoxTenista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxTodas)
                            .addComponent(jCheckBoxNenhuma))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonFoto)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTodasActionPerformed
        jCheckBoxArtista.setSelected(true);
        jCheckBoxColegial.setSelected(true);
        jCheckBoxJardineira.setSelected(true);
        jCheckBoxSurfista.setSelected(true);
        jCheckBoxTenista.setSelected(true); 
    }//GEN-LAST:event_jCheckBoxTodasActionPerformed

    private void jCheckBoxNenhumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNenhumaActionPerformed
        jCheckBoxArtista.setSelected(false);
        jCheckBoxColegial.setSelected(false);
        jCheckBoxJardineira.setSelected(false);
        jCheckBoxSurfista.setSelected(false);
        jCheckBoxTenista.setSelected(false); 
    }//GEN-LAST:event_jCheckBoxNenhumaActionPerformed

    private void jButtonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFotoActionPerformed
        jLabelArtista2.setVisible(jCheckBoxArtista.isSelected());         
        jLabelColegial2.setVisible(jCheckBoxColegial.isSelected());         
        jLabelJardineira2.setVisible(jCheckBoxJardineira.isSelected());         
        jLabelSurfista2.setVisible(jCheckBoxSurfista.isSelected()); 
        jLabelTenista2.setVisible(jCheckBoxTenista.isSelected()); 
        jDialogFoto.setVisible(true);
    }//GEN-LAST:event_jButtonFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FotoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FotoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FotoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FotoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FotoGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonFoto;
    private javax.swing.JCheckBox jCheckBoxArtista;
    private javax.swing.JCheckBox jCheckBoxColegial;
    private javax.swing.JCheckBox jCheckBoxJardineira;
    private javax.swing.JCheckBox jCheckBoxNenhuma;
    private javax.swing.JCheckBox jCheckBoxSurfista;
    private javax.swing.JCheckBox jCheckBoxTenista;
    private javax.swing.JCheckBox jCheckBoxTodas;
    private javax.swing.JDialog jDialogFoto;
    private javax.swing.JLabel jLabelArtista;
    private javax.swing.JLabel jLabelArtista2;
    private javax.swing.JLabel jLabelColegial;
    private javax.swing.JLabel jLabelColegial2;
    private javax.swing.JLabel jLabelJardineira;
    private javax.swing.JLabel jLabelJardineira2;
    private javax.swing.JLabel jLabelSurfista;
    private javax.swing.JLabel jLabelSurfista2;
    private javax.swing.JLabel jLabelTenista;
    private javax.swing.JLabel jLabelTenista2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
