/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividadejogo;

import java.awt.Component;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Asus
 */
public class AppJogo extends javax.swing.JFrame {

    /**
     * Creates new form AppJogo
     */
    public AppJogo() {
        initComponents();
        
        criarTimer();
        timer1.start();
        
        jPanelAreaJogo.setFocusable(true);
        jPanelAreaJogo.addKeyListener(new KeyListener() {

            @Override
            public void keyPressed(KeyEvent e) {
                deslocaBoneco(e);

            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }

            @Override
            public void keyTyped(KeyEvent e) {
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanelAreaJogo = new javax.swing.JPanel();
        jLabelMov = new javax.swing.JLabel();
        jLabelBloco1 = new javax.swing.JLabel();
        jLabelBloco2 = new javax.swing.JLabel();
        jLabelBloco3 = new javax.swing.JLabel();
        jLabelBloco4 = new javax.swing.JLabel();
        jLabelSol = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel6.setText("jLabel6");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelAreaJogo.setBackground(new java.awt.Color(51, 153, 255));
        jPanelAreaJogo.setMinimumSize(new java.awt.Dimension(411, 365));
        jPanelAreaJogo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanelAreaJogoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanelAreaJogo.setLayout(null);

        jLabelMov.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelMov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mad_science_arcade_saturdays_launching_rocket-2.png"))); // NOI18N
        jLabelMov.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelAreaJogo.add(jLabelMov);
        jLabelMov.setBounds(350, 250, 16, 34);

        jLabelBloco1.setBackground(new java.awt.Color(0, 255, 51));
        jLabelBloco1.setText("Use as teclas esquerda e direita para mover o foguete em direção ao sol.");
        jLabelBloco1.setOpaque(true);
        jPanelAreaJogo.add(jLabelBloco1);
        jLabelBloco1.setBounds(0, 334, 411, 31);

        jLabelBloco2.setBackground(new java.awt.Color(153, 51, 0));
        jLabelBloco2.setOpaque(true);
        jPanelAreaJogo.add(jLabelBloco2);
        jLabelBloco2.setBounds(134, 223, 277, 17);

        jLabelBloco3.setBackground(new java.awt.Color(153, 51, 0));
        jLabelBloco3.setOpaque(true);
        jPanelAreaJogo.add(jLabelBloco3);
        jLabelBloco3.setBounds(0, 296, 281, 19);

        jLabelBloco4.setBackground(new java.awt.Color(153, 51, 0));
        jLabelBloco4.setOpaque(true);
        jPanelAreaJogo.add(jLabelBloco4);
        jLabelBloco4.setBounds(0, 143, 282, 19);

        jLabelSol.setBackground(new java.awt.Color(255, 255, 51));
        jLabelSol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/136723.png"))); // NOI18N
        jPanelAreaJogo.add(jLabelSol);
        jLabelSol.setBounds(10, 11, 120, 121);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAreaJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAreaJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelAreaJogoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanelAreaJogoAncestorAdded
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jPanelAreaJogoAncestorAdded

    private void desloca(KeyEvent e) {
        int tecla = e.getKeyCode();
        int x = jLabelMov.getLocation().x;
        int y = jLabelMov.getLocation().y;

        switch (tecla) {
            case KeyEvent.VK_LEFT: // Tecla Esquerda 37
                x = x - 2;
                y = y - 2;
                break;
            case KeyEvent.VK_RIGHT: // Tecla Direita
                x = x + 2;
                y = y - 2;
                break;
        }

        if (!detectaColisaoCom(x, y, jLabelMov.getWidth(), jLabelMov.getHeight())
                && objectoInArea(x, y, jLabelMov.getWidth(), jLabelMov.getHeight())) {
            jLabelMov.setLocation(x, y);
        }

    }

    private boolean detectaColisaoCom(int x, int y, int w, int h) {
        boolean mov = false;
        Component[] c = jPanelAreaJogo.getComponents();
        
        for (int i = 1; i < c.length; i++) {
            Rectangle r1 = new Rectangle(c[i].getLocation().x, c[i].getLocation().y,
                    c[i].getWidth(), c[i].getHeight());
            Rectangle r2 = new Rectangle(x, y, w, h);
            if (r1.intersects(r2)) {
                mov = true;
                System.out.println("valor: "+i);
                if(r2.equals(jLabelSol)){
                    JOptionPane.showMessageDialog(this, "Ganhou o Jogo! Volte sempre!"); 
                    System.exit(0);
                }else{
                    JOptionPane.showMessageDialog(this, "Perdeu o Jogo! Volte sempre!"); 
                    System.exit(0);
                }
            }
            
        }
        return mov;
    }

    private boolean objectoInArea(int x, int y, int h, int w) {
        boolean mov = false;
        Rectangle r1 = new Rectangle(jPanelAreaJogo.getLocation().x, jPanelAreaJogo.getLocation().y,
                jPanelAreaJogo.getWidth(), jPanelAreaJogo.getHeight());
        Rectangle r2 = new Rectangle(x, y, w, h);
        if (r1.contains(r2)) {
            mov = true;
        }
        return mov;
    }

    private void deslocaBoneco(KeyEvent e) {
        // Controlo de movimento do boneco
        int tecla = e.getKeyCode();

        int posXBoneco = jLabelMov.getLocation().x;
        int posYBoneco = jLabelMov.getLocation().y;

        switch (tecla) {
            case 37: // Esquerda e cima
//                jLabelMov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mad_science_arcade_saturdays_launching_rocket-2.png"))); // NOI18N
                posXBoneco = posXBoneco - 2;
                posYBoneco = posYBoneco - 2;
                break;
            case 39: // Direita e cima
//                jLabelMov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mad_science_arcade_saturdays_launching_rocket-2.png"))); // NOI18N

                posXBoneco = posXBoneco + 2;
                posYBoneco = posYBoneco - 2;
                break;
        }
        if (!detectaColisaoCom(posXBoneco, posYBoneco, jLabelMov.getWidth(), jLabelMov.getHeight())
                && objectoInArea(posXBoneco, posYBoneco, jLabelMov.getWidth(), jLabelMov.getHeight())) {
            
            jLabelMov.setLocation(posXBoneco, posYBoneco);
        }

    }
    
    private void criarTimer(){
        timer1 = new javax.swing.Timer(100, new ActionListener(){
            public void actionPerformed(ActionEvent e) {   
                
                    int posXBoneco = jLabelMov.getLocation().x;
                    int posYBoneco = jLabelMov.getLocation().y;
        
                    posYBoneco = posYBoneco + 2;
                    posXBoneco = posXBoneco + 0;
        
                 if (!detectaColisaoCom(posXBoneco, posYBoneco, jLabelMov.getWidth(), jLabelMov.getHeight())
                && objectoInArea(posXBoneco, posYBoneco, jLabelMov.getWidth(), jLabelMov.getHeight())) {   
                jLabelMov.setLocation(posXBoneco, posYBoneco);
                }
            }
        
        });
        }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBloco1;
    private javax.swing.JLabel jLabelBloco2;
    private javax.swing.JLabel jLabelBloco3;
    private javax.swing.JLabel jLabelBloco4;
    private javax.swing.JLabel jLabelMov;
    private javax.swing.JLabel jLabelSol;
    private javax.swing.JPanel jPanelAreaJogo;
    // End of variables declaration//GEN-END:variables

    Timer timer1;
}
