/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExBaseJogo.java
 *
 * Created on 5/Dez/2011, 22:44:03
 */
package basejogo;

import java.awt.Component;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;

/**
 *
 * @author Jose
 */
public class ExBaseJogo extends javax.swing.JFrame {

    /** Creates new form AreaJogo */
    public ExBaseJogo() {
        initComponents();
        carregaImagemBoneco();
        
        jPanelAreaJogo.setFocusable(true);
        jPanelAreaJogo.addKeyListener(new KeyListener() {

            @Override
            public void keyPressed(KeyEvent e) {
                deslocaBoneco(e);
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }

            @Override
            public void keyTyped(KeyEvent e) {
            }
        });
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAreaJogo = new javax.swing.JPanel();
        jLabelMov = new javax.swing.JLabel();
        jLabelBloco1 = new javax.swing.JLabel();
        jLabelBloco2 = new javax.swing.JLabel();
        jLabelBloco3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelAreaJogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelAreaJogo.setLayout(null);

        jLabelMov.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMov.setOpaque(true);
        jPanelAreaJogo.add(jLabelMov);
        jLabelMov.setBounds(160, 80, 30, 30);

        jLabelBloco1.setBackground(new java.awt.Color(0, 0, 204));
        jLabelBloco1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBloco1.setText("Bloco1");
        jLabelBloco1.setOpaque(true);
        jPanelAreaJogo.add(jLabelBloco1);
        jLabelBloco1.setBounds(47, 41, 54, 85);

        jLabelBloco2.setBackground(new java.awt.Color(255, 51, 0));
        jLabelBloco2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBloco2.setText("Bloco2");
        jLabelBloco2.setOpaque(true);
        jPanelAreaJogo.add(jLabelBloco2);
        jLabelBloco2.setBounds(120, 200, 150, 50);

        jLabelBloco3.setBackground(new java.awt.Color(255, 204, 0));
        jLabelBloco3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBloco3.setText("Bloco3");
        jLabelBloco3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelBloco3.setOpaque(true);
        jPanelAreaJogo.add(jLabelBloco3);
        jLabelBloco3.setBounds(280, 30, 31, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAreaJogo, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAreaJogo, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void desloca(KeyEvent e){
        int tecla = e.getKeyCode();
        int x = jLabelMov.getLocation().x;
        int y = jLabelMov.getLocation().y;
        
        switch(tecla){
            case KeyEvent.VK_LEFT: // Tecla Esquerda 37
                x = x - 2;
                break;
            case 39: // Tecla Direita
                x = x + 2;
                break;
            case 38: // Tecla Cima
                y = y - 2;
                break;
            case 40: // Tecla Baixo
                y = y + 2;
                break;
        }

        if (!detectaColisaoCom(x, y,jLabelMov.getHeight(),jLabelMov.getWidth())
                && objectoInArea(x, y,jLabelMov.getHeight(),jLabelMov.getWidth())) 
            jLabelMov.setLocation(x,y);
        

    }
    
    
    private boolean detectaColisaoCom(int x, int y, int h, int w) {
        boolean mov = false;
        Component[] c = jPanelAreaJogo.getComponents();
        for (int i = 1; i < c.length; i++) {
            Rectangle r1 = new Rectangle(c[i].getLocation().x, c[i].getLocation().y,
                                         c[i].getWidth(), c[i].getHeight());
            Rectangle r2 = new Rectangle(x, y, w, h);
            if (r1.intersects(r2)) {
                mov = true;
            }
        }
        return mov;
    }
    
    private boolean objectoInArea(int x, int y, int h, int w) {
        boolean mov = false;
        Rectangle r1 = new Rectangle(jPanelAreaJogo.getLocation().x, jPanelAreaJogo.getLocation().y, 
                                     jPanelAreaJogo.getWidth(), jPanelAreaJogo.getHeight());
        Rectangle r2 = new Rectangle(x, y, w, h);
        if (r1.contains(r2)) {
            mov = true;
        }
        return mov;
    }
    
    
    private void deslocaBoneco(KeyEvent e) {
        // Controlo de movimento do boneco
        int tecla = e.getKeyCode();

        int posXBoneco = jLabelMov.getLocation().x;
        int posYBoneco = jLabelMov.getLocation().y;

        switch (tecla) {
            case 37: // Esquerda
                if (imgDeslocaEsq > 1) {
                    imgDeslocaEsq = 0;
                } else {
                    imgDeslocaEsq++;
                }
                jLabelMov.setIcon((javax.swing.ImageIcon) vBoneco.get(imgDeslocaEsq));
                posXBoneco = posXBoneco - 2;
                break;
            case 39: // Direita
                if (imgDeslocaDir > 4) {
                    imgDeslocaDir = 3;
                } else {
                    imgDeslocaDir++;
                }
                jLabelMov.setIcon((javax.swing.ImageIcon) vBoneco.get(imgDeslocaDir));
                posXBoneco = posXBoneco + 2;
                break;
            case 38: // Cima
                if (imgDeslocaCima > 7) {
                    imgDeslocaCima = 6;
                } else {
                    imgDeslocaCima++;
                }
                jLabelMov.setIcon((javax.swing.ImageIcon) vBoneco.get(imgDeslocaCima));
                posYBoneco = posYBoneco - 2;
                break;
            case 40: // Baixo
                if (imgDeslocaBaixo > 10) {
                    imgDeslocaBaixo = 9;
                } else {
                    imgDeslocaBaixo++;
                }
                jLabelMov.setIcon((javax.swing.ImageIcon) vBoneco.get(imgDeslocaBaixo));
                posYBoneco = posYBoneco + 2;
                break;
        }
        
        if (!detectaColisaoCom(posXBoneco, posYBoneco,jLabelMov.getHeight(),jLabelMov.getWidth())
                && objectoInArea(posXBoneco, posYBoneco,jLabelMov.getHeight(),jLabelMov.getWidth())) 
            jLabelMov.setLocation(posXBoneco,posYBoneco);
        

    }

    private void carregaImagemBoneco() {
        for (int i = 0; i < 3; i++) {
            vBoneco.add(new javax.swing.ImageIcon(getClass().getResource("/imagens/actor1esq" + i + ".png")));
        }
        for (int i = 0; i < 3; i++) {
            vBoneco.add(new javax.swing.ImageIcon(getClass().getResource("/imagens/actor1dir" + i + ".png")));
        }
        for (int i = 0; i < 3; i++) {
            vBoneco.add(new javax.swing.ImageIcon(getClass().getResource("/imagens/actor1tras" + i + ".png")));
        }
        for (int i = 0; i < 3; i++) {
            vBoneco.add(new javax.swing.ImageIcon(getClass().getResource("/imagens/actor1frente" + i + ".png")));
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExBaseJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExBaseJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExBaseJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExBaseJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ExBaseJogo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBloco1;
    private javax.swing.JLabel jLabelBloco2;
    private javax.swing.JLabel jLabelBloco3;
    private javax.swing.JLabel jLabelMov;
    private javax.swing.JPanel jPanelAreaJogo;
    // End of variables declaration//GEN-END:variables

 // Vector com diferentes imagens para deslocar
    ArrayList vBoneco = new ArrayList();
    int imgDeslocaEsq = 0;
    int imgDeslocaDir = 3;
    int imgDeslocaCima = 6;
    int imgDeslocaBaixo = 9;
}
