/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package treinofreqprat2017;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class AppControloDespesas extends javax.swing.JFrame {

    /**
     * Creates new form AppControloDespesas
     */
    public AppControloDespesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAutor = new javax.swing.JDialog();
        jPanelAutor = new javax.swing.JPanel();
        jLabelAutor = new javax.swing.JLabel();
        jLabel2AutorNome = new javax.swing.JLabel();
        jLabelAutorNumero = new javax.swing.JLabel();
        jLabelAnoLetivo = new javax.swing.JLabel();
        jDialogRegistoDespesas = new javax.swing.JDialog();
        jComboBoxRDMes = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabelTipoDeDespesa = new javax.swing.JLabel();
        jComboBoxRDTipoDespesa = new javax.swing.JComboBox<>();
        jLabelDia = new javax.swing.JLabel();
        jComboBoxRDDia = new javax.swing.JComboBox<>();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabel€ = new javax.swing.JLabel();
        jButtonRegistar = new javax.swing.JButton();
        jDialogVerDespesas = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxVDMes = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabelTotal = new javax.swing.JLabel();
        jLabelValorTotal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAplicacao = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuGestao = new javax.swing.JMenu();
        jMenuReceitas = new javax.swing.JMenu();
        jMenuItemRRegistar = new javax.swing.JMenuItem();
        jMenuItemRVer = new javax.swing.JMenuItem();
        jMenuDespesas = new javax.swing.JMenu();
        jMenuItemDRegistar = new javax.swing.JMenuItem();
        jMenuItemDVer = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemAutor = new javax.swing.JMenuItem();

        jDialogAutor.setTitle("Autor");
        jDialogAutor.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialogAutor.setPreferredSize(new java.awt.Dimension(400, 300));

        jPanelAutor.setBackground(new java.awt.Color(204, 204, 255));
        jPanelAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabelAutor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAutor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAutor.setText("Engenharia Informática");

        jLabel2AutorNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2AutorNome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2AutorNome.setText("Daniel Ribeiro");

        jLabelAutorNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAutorNumero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAutorNumero.setText("1012527");

        jLabelAnoLetivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAnoLetivo.setText("2016/17");

        javax.swing.GroupLayout jPanelAutorLayout = new javax.swing.GroupLayout(jPanelAutor);
        jPanelAutor.setLayout(jPanelAutorLayout);
        jPanelAutorLayout.setHorizontalGroup(
            jPanelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAutorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAutorNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2AutorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(jPanelAutorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAnoLetivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAutorLayout.setVerticalGroup(
            jPanelAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAutorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2AutorNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAutorNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAnoLetivo)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogAutorLayout = new javax.swing.GroupLayout(jDialogAutor.getContentPane());
        jDialogAutor.getContentPane().setLayout(jDialogAutorLayout);
        jDialogAutorLayout.setHorizontalGroup(
            jDialogAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAutorLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jPanelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jDialogAutorLayout.setVerticalGroup(
            jDialogAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAutorLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jDialogAutor.getAccessibleContext().setAccessibleName("Autor");

        jDialogRegistoDespesas.setTitle("Registo de Despesas");
        jDialogRegistoDespesas.setMinimumSize(new java.awt.Dimension(400, 300));

        jComboBoxRDMes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxRDMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRDMes.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxRDMesPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Despesas"));

        jLabelTipoDeDespesa.setText("Tipo de Despesa:");

        jComboBoxRDTipoDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelDia.setText("Dia:");

        jComboBoxRDDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelValor.setText("Valor:");

        jTextFieldValor.setText("jTextField1");

        jLabel€.setText("€");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTipoDeDespesa)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxRDTipoDespesa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxRDDia, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel€, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoDeDespesa)
                    .addComponent(jComboBoxRDTipoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDia)
                    .addComponent(jComboBoxRDDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValor)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel€))
                .addGap(23, 23, 23))
        );

        jButtonRegistar.setText("Registar");
        jButtonRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogRegistoDespesasLayout = new javax.swing.GroupLayout(jDialogRegistoDespesas.getContentPane());
        jDialogRegistoDespesas.getContentPane().setLayout(jDialogRegistoDespesasLayout);
        jDialogRegistoDespesasLayout.setHorizontalGroup(
            jDialogRegistoDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogRegistoDespesasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jDialogRegistoDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxRDMes, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogRegistoDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonRegistar)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jDialogRegistoDespesasLayout.setVerticalGroup(
            jDialogRegistoDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogRegistoDespesasLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jComboBoxRDMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegistar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jDialogVerDespesas.setMinimumSize(new java.awt.Dimension(400, 300));

        jComboBoxVDMes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxVDMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxVDMes.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxVDMesPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Dia", "Tipo de Despesa", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setMinimumSize(new java.awt.Dimension(45, 0));
        jScrollPane2.setViewportView(jTable);

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotal.setText("Total:");

        jLabelValorTotal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelValorTotal.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jComboBoxVDMes, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabelTotal)
                .addGap(18, 18, 18)
                .addComponent(jLabelValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jComboBoxVDMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTotal)
                    .addComponent(jLabelValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogVerDespesasLayout = new javax.swing.GroupLayout(jDialogVerDespesas.getContentPane());
        jDialogVerDespesas.getContentPane().setLayout(jDialogVerDespesasLayout);
        jDialogVerDespesasLayout.setHorizontalGroup(
            jDialogVerDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogVerDespesasLayout.setVerticalGroup(
            jDialogVerDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Despesas Familiares");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenuAplicacao.setText("Aplicação");

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuAplicacao.add(jMenuItemSair);

        jMenuBar1.add(jMenuAplicacao);

        jMenuGestao.setText("Gestão");

        jMenuReceitas.setText("Receitas");

        jMenuItemRRegistar.setText("Registar");
        jMenuReceitas.add(jMenuItemRRegistar);

        jMenuItemRVer.setText("Ver");
        jMenuReceitas.add(jMenuItemRVer);

        jMenuGestao.add(jMenuReceitas);

        jMenuDespesas.setText("Despesas");

        jMenuItemDRegistar.setText("Registar");
        jMenuItemDRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDRegistarActionPerformed(evt);
            }
        });
        jMenuDespesas.add(jMenuItemDRegistar);

        jMenuItemDVer.setText("Ver");
        jMenuItemDVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDVerActionPerformed(evt);
            }
        });
        jMenuDespesas.add(jMenuItemDVer);

        jMenuGestao.add(jMenuDespesas);

        jMenuBar1.add(jMenuGestao);

        jMenuAjuda.setText("Ajuda");

        jMenuItemAutor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAutor.setText("Autor");
        jMenuItemAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAutorActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemAutor);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAutorActionPerformed
        jDialogAutor.setVisible(true);
    }//GEN-LAST:event_jMenuItemAutorActionPerformed

    private void jMenuItemDRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDRegistarActionPerformed
        lerTiposDespesa();
        jDialogRegistoDespesas.setVisible(true);
    }//GEN-LAST:event_jMenuItemDRegistarActionPerformed

    private void jMenuItemDVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDVerActionPerformed
        jDialogVerDespesas.setVisible(true);
    }//GEN-LAST:event_jMenuItemDVerActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jComboBoxRDMesPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxRDMesPopupMenuWillBecomeInvisible
        int mes = jComboBoxRDMes.getSelectedIndex();
        jComboBoxRDDia.removeAllItems();
        for (int i=1;i<=diasMes(mes);i++){
            jComboBoxRDDia.addItem(""+i);
        }
    }//GEN-LAST:event_jComboBoxRDMesPopupMenuWillBecomeInvisible

    private void jButtonRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistarActionPerformed
        int mes = jComboBoxRDMes.getSelectedIndex()+1;
        String tipoDespesa = jComboBoxRDTipoDespesa.getSelectedItem().toString();
        int dia = jComboBoxRDDia.getSelectedIndex()+1;
        double valor = Double.parseDouble(jTextFieldValor.getText());
        
        inserirRegisto(mes, tipoDespesa, dia, valor);
    }//GEN-LAST:event_jButtonRegistarActionPerformed

    private void jComboBoxVDMesPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxVDMesPopupMenuWillBecomeInvisible
        int mes = jComboBoxVDMes.getSelectedIndex()+1;
        lerDespesasPorMes(mes);
    }//GEN-LAST:event_jComboBoxVDMesPopupMenuWillBecomeInvisible

    private void lerDespesasPorMes(int mes){
        String url = "jdbc:sqlite:BDReceitasDespesas";
        Connection con;
        Statement stmt;
        DefaultTableModel modelo = (DefaultTableModel)jTable.getModel();
        modelo.setRowCount(0);
        try {
            Class.forName("org.sqlite.JDBC");
        } catch(java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }
        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from RegistoDespesa where mes = "+mes );
            double total = 0;
            while (rs.next()) {	
            		int dia = rs.getInt("Dia");
                        String tipo = rs.getString("TipoDespesa");
                        double valor = rs.getDouble("Valor");
                        total = total + valor;
                        Object rowData[] = {dia,tipo,valor};
                        modelo.addRow(rowData);
	    }
            jLabelValorTotal.setText(""+total);
            stmt.close();
            con.close();
        } catch(SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
        
    }
    
    private void inserirRegisto(int mes,String tipo, int dia, double valor){
        String url = "jdbc:sqlite:BDReceitasDespesas";
        Connection con;
        Statement stmt;

        try {
            Class.forName("org.sqlite.JDBC");
        } catch(java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }

        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            stmt.executeUpdate("INSERT INTO RegistoDespesa " +
            	 "VALUES ("+mes+",'"+tipo+"',"+dia+","+valor+")");
        	 
            stmt.close();
            con.close();
            

        } catch(SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
        
    }
    
    private int diasMes(int mes){
        int m[] = {31,29,31,30,31,30,31,31,30,31,30,31};
        return m[mes];
    }
    
    private void lerTiposDespesa(){
        String url = "jdbc:sqlite:BDReceitasDespesas";
        Connection con;
        Statement stmt;
        jComboBoxRDTipoDespesa.removeAllItems();
        try {
            Class.forName("org.sqlite.JDBC");
        } catch(java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }
        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from TipoDespesa");
            jComboBoxRDTipoDespesa.addItem("-- Escolha o Tipo de Despesa --");
            while (rs.next()) {	
            		String tipo = rs.getString("Tipo");
                        jComboBoxRDTipoDespesa.addItem(tipo);
	    }
            stmt.close();
            con.close();
        } catch(SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppControloDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppControloDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppControloDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppControloDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppControloDespesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistar;
    private javax.swing.JComboBox<String> jComboBoxRDDia;
    private javax.swing.JComboBox<String> jComboBoxRDMes;
    private javax.swing.JComboBox<String> jComboBoxRDTipoDespesa;
    private javax.swing.JComboBox<String> jComboBoxVDMes;
    private javax.swing.JDialog jDialogAutor;
    private javax.swing.JDialog jDialogRegistoDespesas;
    private javax.swing.JDialog jDialogVerDespesas;
    private javax.swing.JLabel jLabel2AutorNome;
    private javax.swing.JLabel jLabelAnoLetivo;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelAutorNumero;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelTipoDeDespesa;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JLabel jLabelValorTotal;
    private javax.swing.JLabel jLabel€;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuAplicacao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDespesas;
    private javax.swing.JMenu jMenuGestao;
    private javax.swing.JMenuItem jMenuItemAutor;
    private javax.swing.JMenuItem jMenuItemDRegistar;
    private javax.swing.JMenuItem jMenuItemDVer;
    private javax.swing.JMenuItem jMenuItemRRegistar;
    private javax.swing.JMenuItem jMenuItemRVer;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuReceitas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAutor;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
