/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividade06;

import javax.swing.ImageIcon;

/**
 *
 * @author Asus
 */
public class Caras extends javax.swing.JFrame {

    /**
     * Creates new form Caras
     */
    public Caras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCabelo = new javax.swing.JLabel();
        jLabelOlhos = new javax.swing.JLabel();
        jLabelBoca = new javax.swing.JLabel();
        jComboBoxCabelo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxOlhos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxBoca = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxPessoa = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mix Caras");

        jPanel1.setLayout(null);

        jLabelCabelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCabelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensFaces/Foto1Cabelo.jpg"))); // NOI18N
        jLabelCabelo.setText("jLabel1");
        jLabelCabelo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabelCabelo);
        jLabelCabelo.setBounds(210, 40, 160, 50);

        jLabelOlhos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOlhos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensFaces/Foto1Olhos.jpg"))); // NOI18N
        jLabelOlhos.setText("jLabel2");
        jPanel1.add(jLabelOlhos);
        jLabelOlhos.setBounds(210, 100, 160, 50);

        jLabelBoca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBoca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensFaces/Foto1Boca.jpg"))); // NOI18N
        jLabelBoca.setText("jLabel3");
        jLabelBoca.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabelBoca);
        jLabelBoca.setBounds(210, 160, 160, 70);

        jComboBoxCabelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Foto1", "Foto2", "Foto3", "Foto4" }));
        jComboBoxCabelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCabeloActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCabelo);
        jComboBoxCabelo.setBounds(90, 60, 53, 20);

        jLabel1.setText("Cabelo:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 60, 70, 14);

        jComboBoxOlhos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Foto1", "Foto2", "Foto3", "Foto4" }));
        jComboBoxOlhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOlhosActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxOlhos);
        jComboBoxOlhos.setBounds(90, 110, 53, 20);

        jLabel2.setText("Olhos:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(21, 110, 50, 14);

        jComboBoxBoca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Foto1", "Foto2", "Foto3", "Foto4" }));
        jComboBoxBoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBocaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBoca);
        jComboBoxBoca.setBounds(90, 160, 53, 20);

        jLabel3.setText("Boca:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(17, 160, 50, 14);

        jComboBoxPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Foto1", "Foto2", "Foto3", "Foto4" }));
        jComboBoxPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPessoaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxPessoa);
        jComboBoxPessoa.setBounds(90, 10, 53, 20);

        jLabel4.setText("Pessoa:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 10, 70, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCabeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCabeloActionPerformed
        String foto = jComboBoxCabelo.getSelectedItem().toString();         
        ImageIcon imagem = new javax.swing.ImageIcon(getClass().getResource("/imagensFaces/"+foto+"Cabelo.jpg"));        
        jLabelCabelo.setIcon(imagem);
    }//GEN-LAST:event_jComboBoxCabeloActionPerformed

    private void jComboBoxOlhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOlhosActionPerformed
         String foto = jComboBoxOlhos.getSelectedItem().toString();         
         ImageIcon imagem = new javax.swing.ImageIcon(getClass().getResource("/imagensFaces/"+foto+"Olhos.jpg"));         
         jLabelOlhos.setIcon(imagem); 
    }//GEN-LAST:event_jComboBoxOlhosActionPerformed

    private void jComboBoxBocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBocaActionPerformed
         String foto = jComboBoxBoca.getSelectedItem().toString();
         ImageIcon imagem = new javax.swing.ImageIcon(getClass().getResource("/imagensFaces/"+foto+"Boca.jpg"));
         jLabelBoca.setIcon(imagem); 
    }//GEN-LAST:event_jComboBoxBocaActionPerformed

    private void jComboBoxPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPessoaActionPerformed
        String foto = jComboBoxPessoa.getSelectedItem().toString();
        ImageIcon imagemCabelo = new javax.swing.ImageIcon(getClass().getResource("/imagensFaces/"+foto+"Cabelo.jpg"));
        ImageIcon imagemOlhos = new javax.swing.ImageIcon(getClass().getResource("/imagensFaces/"+foto+"Olhos.jpg"));
        ImageIcon imagemBoca = new javax.swing.ImageIcon(getClass().getResource("/imagensFaces/"+foto+"Boca.jpg"));
        jLabelCabelo.setIcon(imagemCabelo);
        jLabelOlhos.setIcon(imagemOlhos);
        jLabelBoca.setIcon(imagemBoca);
    }//GEN-LAST:event_jComboBoxPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxBoca;
    private javax.swing.JComboBox<String> jComboBoxCabelo;
    private javax.swing.JComboBox<String> jComboBoxOlhos;
    private javax.swing.JComboBox<String> jComboBoxPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBoca;
    private javax.swing.JLabel jLabelCabelo;
    private javax.swing.JLabel jLabelOlhos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
